# Production overrides for Project Sentinel.

model:
  productionReference: "957c15c4b33848b4841141074c66bdb8"

api:
  replicaCount: 3

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
