registry:
  existingPullSecret: ""

worker:
  autoInference:
    enabled: true

driftDetection:
  enabled: true

  window: "5m"
  minimumPredictions: 20

  predictionDistribution:
    maxClassShare: 0.80

  alertFor: "1m"

prometheus:
  service:
    type: ClusterIP

alertmanager:
  enabled: true

grafana:
  service:
    type: ClusterIP