{{- if .Values.inferenceRunner.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: sentinel-inference-runner
  labels:
    app.kubernetes.io/name: sentinel-inference-runner
    app.kubernetes.io/component: inference-orchestration
    app.kubernetes.io/part-of: sentinel

spec:
  replicas: {{ .Values.inferenceRunner.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: sentinel-inference-runner

  template:
    metadata:
      labels:
        app.kubernetes.io/name: sentinel-inference-runner
        app.kubernetes.io/component: inference-orchestration
        app.kubernetes.io/part-of: sentinel

    spec:
      {{- if .Values.registry.existingPullSecret }}
      imagePullSecrets:
        - name: {{ .Values.registry.existingPullSecret | quote }}
      {{- end }}

      containers:
        - name: inference-runner
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}

          command:
            - python
            - -m
            - sentinel.consumers.inference_runner

          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: sentinel-common-config
                  key: LOG_LEVEL

            - name: SENTINEL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: sentinel-common-config
                  key: SENTINEL_API_URL

            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: sentinel-common-config
                  key: RABBITMQ_HOST

            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: sentinel-common-config
                  key: RABBITMQ_PORT

            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret | quote }}
                  key: RABBITMQ_USERNAME

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret | quote }}
                  key: RABBITMQ_PASSWORD

          resources:
            requests:
              cpu: {{ .Values.inferenceRunner.resources.requests.cpu | quote }}
              memory: {{ .Values.inferenceRunner.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.inferenceRunner.resources.limits.cpu | quote }}
              memory: {{ .Values.inferenceRunner.resources.limits.memory | quote }}
{{- end }}
