apiVersion: v1
kind: ConfigMap

metadata:
  name: sentinel-common-config
  namespace: default
  labels:
    app.kubernetes.io/name: sentinel
    app.kubernetes.io/component: configuration

data:
  LOG_LEVEL: "INFO"

  RABBITMQ_HOST: "rabbitmq-0.rabbitmq-headless.default.svc.cluster.local"
  RABBITMQ_PORT: "5672"

  REDIS_HOST: "redis-0.redis-headless.default.svc.cluster.local"
  REDIS_PORT: "6379"

  POSTGRES_HOST: "postgres-0.postgres-headless.default.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "sentinel"