clearml:
  apiHost: "http://host.minikube.internal:8008"
  filesHost: "http://192.168.49.1:8081"
  webHost: "http://host.minikube.internal:8080"
  servingTaskId: "29e0f63937284e5fb4a3d2a4bf53d5f0"
  defaultBaseServeUrl: "http://clearml-serving-inference:8080/serve"
  kafkaServeUrl: ""

clearml_serving_inference:
  image:
    repository: "allegroai/clearml-serving-inference"
    tag: "1.3.1"

  pollFrequencyMinutes: "0.25"


  autoscaling:
    enabled: false

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

clearml_serving_triton:
  enabled: true

  image:
    repository: "allegroai/clearml-serving-triton"
    tag: "1.3.1"

  pollFrequencyMinutes: "0.25"
  metricFrequencyMinutes: "1.0"


  autoscaling:
    enabled: false

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

clearml_serving_statistics:
  enabled: false

kafka:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
